#include "model/ResourceNames.h"

#include <QHash>

namespace newage {

namespace {

// Ported from Advanced Genie Editor: the default civ resource names that
// AGE_Frame/Lists.cpp writes to AGE3NamesV0007.ini.
QStringList buildResourceNames(genie::GameVersion version)
{
    QStringList names;
    if (version < genie::GV_AoKE3)
    {
        names.append(QStringLiteral("Food Storage"));
        names.append(QStringLiteral("Wood Storage"));
        names.append(QStringLiteral("Stone Storage"));
        names.append(QStringLiteral("Gold Storage"));
        names.append(QStringLiteral("Population Headroom"));
        names.append(QStringLiteral("Conversion Range"));
        names.append(QStringLiteral("Current Age"));
        names.append(QStringLiteral("Artifacts Captured"));
        names.append(QStringLiteral("Unused (Trade Bonus)"));
        names.append(QStringLiteral("Trade Goods"));
        names.append(QStringLiteral("Trade Production"));
        names.append(QStringLiteral("Current Population"));
        names.append(QStringLiteral("Corpse Decay Time"));
        names.append(QStringLiteral("Remarkable Discovery"));
        names.append(QStringLiteral("Ruins Captured"));
        names.append(QStringLiteral("Meat Storage"));
        names.append(QStringLiteral("Berry Storage"));
        names.append(QStringLiteral("Fish Storage"));
        names.append(QStringLiteral("Unused (Trade Tax)"));
        names.append(QStringLiteral("Total Units Owned"));
        names.append(QStringLiteral("Units Killed"));
        names.append(QStringLiteral("Technology Count"));
        names.append(QStringLiteral("% Map Explored"));
        names.append(QStringLiteral("Bronze Age Tech ID"));
        names.append(QStringLiteral("Iron Age Tech ID"));
        names.append(QStringLiteral("Tool Age Tech ID"));
        names.append(QStringLiteral("Attack Warning Sound ID"));
        names.append(QStringLiteral("Enable Priest Conversion"));
        names.append(QStringLiteral("Enable Building Conversion"));
        names.append(QStringLiteral("Bribery (Gold Cost Replace)"));
        names.append(QStringLiteral("Unused (Building Limit)"));
        names.append(QStringLiteral("Unused (Food Limit)"));
        names.append(QStringLiteral("Unit Limit"));
        names.append(QStringLiteral("Food Maintenance"));
        names.append(QStringLiteral("Faith"));
        names.append(QStringLiteral("Faith Recharging Rate"));
        names.append(QStringLiteral("Farm Food Amount"));
        names.append(QStringLiteral("Civilian Population"));
        names.append(QStringLiteral("Unused"));
        names.append(QStringLiteral("All Techs Achieved"));
        names.append(QStringLiteral("Military Population"));
        names.append(QStringLiteral("Conversions"));
        names.append(QStringLiteral("Standing Wonders"));
        names.append(QStringLiteral("Razings"));
        names.append(QStringLiteral("Kill Ratio"));
        names.append(QStringLiteral("Survival to Finish"));
        names.append(QStringLiteral("Tribute Inefficiency"));
        names.append(QStringLiteral("Gold Mining Productivity"));
        names.append(QStringLiteral("Town Center Unavailable"));
        names.append(QStringLiteral("Gold Counter"));
        names.append(QStringLiteral("Reveal Ally"));
        names.append(QStringLiteral("Unused (Houses)"));
        names.append(QStringLiteral("Temples"));
        names.append(QStringLiteral("Tribute Sent"));
        names.append(QStringLiteral("All Ruins Captured"));
        names.append(QStringLiteral("All Artifacts Captured"));
        if (version >= genie::GV_RoR)
        {
            names.append(QStringLiteral("Heal Bonus"));
            names.append(QStringLiteral("Martyrdom"));
        }
    }
    else if (version < genie::GV_SWGB)
    {
        names.append(QStringLiteral("Food Storage"));
        names.append(QStringLiteral("Wood Storage"));
        names.append(QStringLiteral("Stone Storage"));
        names.append(QStringLiteral("Gold Storage"));
        names.append(QStringLiteral("Population Headroom"));
        names.append(QStringLiteral("Conversion Range"));
        names.append(QStringLiteral("Current Age"));
        names.append(QStringLiteral("Relics Captured"));
        names.append(QStringLiteral("Unused (Trade Bonus)"));
        names.append(QStringLiteral("Trade Goods"));
        names.append(QStringLiteral("Unused (Trade Production)"));
        names.append(QStringLiteral("Current Population"));
        names.append(QStringLiteral("Corpse Decay Time"));
        names.append(QStringLiteral("Remarkable Discovery"));
        names.append(QStringLiteral("Monuments Captured"));
        names.append(QStringLiteral("Meat Storage"));
        names.append(QStringLiteral("Berry Storage"));
        names.append(QStringLiteral("Fish Storage"));
        names.append(QStringLiteral("Unused"));
        names.append(QStringLiteral("Total Units Owned"));
        names.append(QStringLiteral("Units Killed"));
        names.append(QStringLiteral("Technology Count"));
        names.append(QStringLiteral("% Map Explored"));
        names.append(QStringLiteral("Castle Age Tech ID"));
        names.append(QStringLiteral("Imperial Age Tech ID"));
        names.append(QStringLiteral("Feudal Age Tech ID"));
        names.append(QStringLiteral("Attack Warning Sound ID"));
        names.append(QStringLiteral("Enable Monk Conversion"));
        names.append(QStringLiteral("Enable Building Conversion"));
        names.append(QStringLiteral("Unused"));
        names.append(QStringLiteral("Unused (Building Limit)"));
        names.append(QStringLiteral("Unused (Food Limit)"));
        names.append(QStringLiteral("Bonus Population Cap"));
        names.append(QStringLiteral("Food Maintenance"));
        names.append(QStringLiteral("Faith"));
        names.append(QStringLiteral("Faith Recharging Rate"));
        names.append(QStringLiteral("Farm Food Amount"));
        names.append(QStringLiteral("Civilian Population"));
        names.append(QStringLiteral("Unused"));
        names.append(QStringLiteral("All Techs Achieved"));
        names.append(QStringLiteral("Military Population"));
        names.append(QStringLiteral("Conversions"));
        names.append(QStringLiteral("Standing Wonders"));
        names.append(QStringLiteral("Razings"));
        names.append(QStringLiteral("Kill Ratio"));
        names.append(QStringLiteral("Survival to Finish"));
        names.append(QStringLiteral("Tribute Inefficiency"));
        names.append(QStringLiteral("Gold Mining Productivity"));
        names.append(QStringLiteral("Town Center Unavailable"));
        names.append(QStringLiteral("Gold Counter"));
        names.append(QStringLiteral("Reveal Ally"));
        names.append(QStringLiteral("Unused (Houses)"));
        names.append(QStringLiteral("Monasteries"));
        names.append(QStringLiteral("Tribute Sent"));
        names.append(QStringLiteral("All Monuments Captured"));
        names.append(QStringLiteral("All Relics Captured"));
        names.append(QStringLiteral("Ore Storage"));
        names.append(QStringLiteral("Kidnap Storage"));
        names.append(QStringLiteral("Dark Age Tech ID"));
        names.append(QStringLiteral("Unused (Trade Good Quality)"));
        names.append(QStringLiteral("Unused (Trade Market Level)"));
        names.append(QStringLiteral("Unused (Formations)"));
        names.append(QStringLiteral("Building Housing Rate"));
        names.append(QStringLiteral("Tax Gather Rate"));
        names.append(QStringLiteral("Gather Accumulator"));
        names.append(QStringLiteral("Salvage Decay Rate"));
        names.append(QStringLiteral("Unused (Allow Formations)"));
        names.append(QStringLiteral("Can Convert"));
        names.append(QStringLiteral("Hit Points Killed"));
        if (version >= genie::GV_C2)
        {
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
        }
        else
        {
            names.append(QStringLiteral("Killed P1"));
            names.append(QStringLiteral("Killed P2"));
            names.append(QStringLiteral("Killed P3"));
            names.append(QStringLiteral("Killed P4"));
            names.append(QStringLiteral("Killed P5"));
            names.append(QStringLiteral("Killed P6"));
            names.append(QStringLiteral("Killed P7"));
            names.append(QStringLiteral("Killed P8"));
        }
        names.append(QStringLiteral("Conversion Resistance"));
        names.append(QStringLiteral("Trade Vig Rate"));
        names.append(QStringLiteral("Stone Mining Productivity"));
        names.append(QStringLiteral("Queued Units"));
        names.append(QStringLiteral("Training Count"));
        names.append(QStringLiteral("Start with Unit 444 (PTWC)"));
        names.append(QStringLiteral("Boarding Recharge Rate"));
        names.append(QStringLiteral("Starting Villagers"));
        names.append(QStringLiteral("Research Cost Modifier"));
        names.append(QStringLiteral("Research Time Modifier"));
        names.append(QStringLiteral("Convert Boats"));
        names.append(QStringLiteral("Fish Trap Food Amount"));
        names.append(QStringLiteral("Heal Rate Modifier"));
        names.append(QStringLiteral("Healing Range"));
        names.append(QStringLiteral("Starting Food"));
        names.append(QStringLiteral("Starting Wood"));
        names.append(QStringLiteral("Starting Stone"));
        names.append(QStringLiteral("Starting Gold"));
        names.append(QStringLiteral("Enable PTWC / Kidnap / Loot"));
        names.append(QStringLiteral("Berserker Heal Timer"));
        names.append(QStringLiteral("Dominant Sheep Control"));
        names.append(QStringLiteral("Building Cost Sum"));
        names.append(QStringLiteral("Tech Cost Sum"));
        names.append(QStringLiteral("Relic Income Sum"));
        names.append(QStringLiteral("Trade Income Sum"));
        if (version >= genie::GV_C2)
        {
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
        }
        else
        {
            names.append(QStringLiteral("P1 Tribute"));
            names.append(QStringLiteral("P2 Tribute"));
            names.append(QStringLiteral("P3 Tribute"));
            names.append(QStringLiteral("P4 Tribute"));
            names.append(QStringLiteral("P5 Tribute"));
            names.append(QStringLiteral("P6 Tribute"));
            names.append(QStringLiteral("P7 Tribute"));
            names.append(QStringLiteral("P8 Tribute"));
            names.append(QStringLiteral("P1 Kill Value"));
            names.append(QStringLiteral("P2 Kill Value"));
            names.append(QStringLiteral("P3 Kill Value"));
            names.append(QStringLiteral("P4 Kill Value"));
            names.append(QStringLiteral("P5 Kill Value"));
            names.append(QStringLiteral("P6 Kill Value"));
            names.append(QStringLiteral("P7 Kill Value"));
            names.append(QStringLiteral("P8 Kill Value"));
            names.append(QStringLiteral("P1 Razings"));
            names.append(QStringLiteral("P2 Razings"));
            names.append(QStringLiteral("P3 Razings"));
            names.append(QStringLiteral("P4 Razings"));
            names.append(QStringLiteral("P5 Razings"));
            names.append(QStringLiteral("P6 Razings"));
            names.append(QStringLiteral("P7 Razings"));
            names.append(QStringLiteral("P8 Razings"));
            names.append(QStringLiteral("P1 Razing Value"));
            names.append(QStringLiteral("P2 Razing Value"));
            names.append(QStringLiteral("P3 Razing Value"));
            names.append(QStringLiteral("P4 Razing Value"));
            names.append(QStringLiteral("P5 Razing Value"));
            names.append(QStringLiteral("P6 Razing Value"));
            names.append(QStringLiteral("P7 Razing Value"));
            names.append(QStringLiteral("P8 Razing Value"));
        }
        names.append(QStringLiteral("Standing Castles"));
        names.append(QStringLiteral("Hit Points Razed"));
        if (version >= genie::GV_C2)
        {
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
        }
        else
        {
            names.append(QStringLiteral("Kills by P1"));
            names.append(QStringLiteral("Kills by P2"));
            names.append(QStringLiteral("Kills by P3"));
            names.append(QStringLiteral("Kills by P4"));
            names.append(QStringLiteral("Kills by P5"));
            names.append(QStringLiteral("Kills by P6"));
            names.append(QStringLiteral("Kills by P7"));
            names.append(QStringLiteral("Kills by P8"));
            names.append(QStringLiteral("Razings by P1"));
            names.append(QStringLiteral("Razings by P2"));
            names.append(QStringLiteral("Razings by P3"));
            names.append(QStringLiteral("Razings by P4"));
            names.append(QStringLiteral("Razings by P5"));
            names.append(QStringLiteral("Razings by P6"));
            names.append(QStringLiteral("Razings by P7"));
            names.append(QStringLiteral("Razings by P8"));
        }
        names.append(QStringLiteral("Value Killed by Others"));
        names.append(QStringLiteral("Value Razed by Others"));
        names.append(QStringLiteral("Killed by Others"));
        names.append(QStringLiteral("Razed by Others"));
        if (version >= genie::GV_C2)
        {
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
            names.append(QStringLiteral("Unused"));
        }
        else
        {
            names.append(QStringLiteral("Tribute from P1"));
            names.append(QStringLiteral("Tribute from P2"));
            names.append(QStringLiteral("Tribute from P3"));
            names.append(QStringLiteral("Tribute from P4"));
            names.append(QStringLiteral("Tribute from P5"));
            names.append(QStringLiteral("Tribute from P6"));
            names.append(QStringLiteral("Tribute from P7"));
            names.append(QStringLiteral("Tribute from P8"));
        }
        names.append(QStringLiteral("Value Current Units"));
        names.append(QStringLiteral("Value Current Buildings"));
        names.append(QStringLiteral("Food Total"));
        names.append(QStringLiteral("Wood Total"));
        names.append(QStringLiteral("Stone Total"));
        names.append(QStringLiteral("Gold Total"));
        names.append(QStringLiteral("Total Value of Kills"));
        names.append(QStringLiteral("Total Tribute Received"));
        names.append(QStringLiteral("Total Value of Razings"));
        names.append(QStringLiteral("Total Castles Built"));
        names.append(QStringLiteral("Total Wonders Built"));
        names.append(QStringLiteral("Tribute Score"));
        names.append(QStringLiteral("Convert Min Adjustment"));
        names.append(QStringLiteral("Convert Max Adjustment"));
        names.append(QStringLiteral("Convert Resist Min Adjustment"));
        names.append(QStringLiteral("Convert Resist Max Adjustment"));
        names.append(QStringLiteral("Convert Building Min"));
        names.append(QStringLiteral("Convert Building Max"));
        names.append(QStringLiteral("Convert Building Chance"));
        names.append(QStringLiteral("Reveal Enemy"));
        names.append(QStringLiteral("Value Wonders Castles"));
        names.append(QStringLiteral("Food Score"));
        names.append(QStringLiteral("Wood Score"));
        names.append(QStringLiteral("Stone Score"));
        names.append(QStringLiteral("Gold Score")); // 188 Age of Kings ends here
        if (version >= genie::GV_TC)
        {
            names.append(QStringLiteral("Chopping Productivity"));
            names.append(QStringLiteral("Food-gathering Productivity"));
            names.append(QStringLiteral("Relic Gold Production Rate"));
            names.append(QStringLiteral("Converted Units Die"));
            names.append(QStringLiteral("Theocracy"));
            names.append(QStringLiteral("Crenellations"));
            names.append(QStringLiteral("Construction Rate Modifier"));
            names.append(QStringLiteral("Hun Wonder Bonus"));
            names.append(QStringLiteral("Spies Discount")); // 197 Conquerors ends here
            if (version >= genie::GV_Cysion)
            {
                names.append(QStringLiteral("Unused"));
                names.append(QStringLiteral("Unused"));
                names.append(QStringLiteral("Unused"));
                names.append(QStringLiteral("Unused"));
                names.append(QStringLiteral("Unused"));
                names.append(QStringLiteral("Unused"));
                names.append(QStringLiteral("Unused"));
                names.append(QStringLiteral("Feitoria Food Productivity"));
                names.append(QStringLiteral("Feitoria Wood Productivity"));
                names.append(QStringLiteral("Feitoria Stone Productivity"));
                names.append(QStringLiteral("Feitoria Gold Productivity")); // 208 African Kingdoms ends here
                names.append(QStringLiteral("Reveal Enemy Town Centers"));
                names.append(QStringLiteral("Relics Visible on Map")); // 210 Rise of the Rajas ends here
                if (version >= genie::GV_C2)
                {
                    names.append(QStringLiteral("Higher Elevation Bonus"));
                    names.append(QStringLiteral("Lower Elevation Bonus"));
                    names.append(QStringLiteral("Raiding Productivity"));
                    names.append(QStringLiteral("Mercenary Kipchak Count"));
                    names.append(QStringLiteral("Mercenary Kipchak Limit"));
                    names.append(QStringLiteral("Shepherd Productivity"));
                    names.append(QStringLiteral("Trigger Shared Visibility"));
                    names.append(QStringLiteral("Early Town Center Limit"));
                    names.append(QStringLiteral("Fishing Productivity"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Monument Food Productivity"));
                    names.append(QStringLiteral("Monument Wood Productivity"));
                    names.append(QStringLiteral("Monument Stone Productivity"));
                    names.append(QStringLiteral("Monument Gold Productivity"));
                    names.append(QStringLiteral("Relic Food Production Rate"));
                    names.append(QStringLiteral("Villagers Killed By Gaia"));
                    names.append(QStringLiteral("Villagers Killed By Animals"));
                    names.append(QStringLiteral("Villagers Killed By AI Players"));
                    names.append(QStringLiteral("Villagers Killed By Human Players"));
                    names.append(QStringLiteral("Battle Royale Food Generation"));
                    names.append(QStringLiteral("Battle Royale Wood Generation"));
                    names.append(QStringLiteral("Battle Royale Stone Generation"));
                    names.append(QStringLiteral("Battle Royale Gold Generation"));
                    names.append(QStringLiteral("Spawn Cap"));
                    names.append(QStringLiteral("Flemish Militia Population"));
                    names.append(QStringLiteral("Farming Gold Productivity"));
                    names.append(QStringLiteral("Folwark Collect Amount"));
                    names.append(QStringLiteral("Folwark Collect Resource Type"));
                    names.append(QStringLiteral("Folwark Building ID"));
                    names.append(QStringLiteral("Units Converted"));
                    names.append(QStringLiteral("Stone Mining Gold Productivity"));
                    names.append(QStringLiteral("Workshop Food Generation"));
                    names.append(QStringLiteral("Workshop Wood Generation"));
                    names.append(QStringLiteral("Workshop Stone Generation"));
                    names.append(QStringLiteral("Workshop Gold Generation"));
                    names.append(QStringLiteral("Total Build Value Units"));
                    names.append(QStringLiteral("Total Build Value Buildings"));
                    names.append(QStringLiteral("Total Villagers Created"));
                    names.append(QStringLiteral("Total Villager Idle Periods"));
                    names.append(QStringLiteral("Total Villager Idle Seconds")); // 250 Dawn of the Dukes ends here
                    names.append(QStringLiteral("Trade Food Percent"));
                    names.append(QStringLiteral("Trade Wood Percent"));
                    names.append(QStringLiteral("Trade Stone Percent"));
                    names.append(QStringLiteral("Livestock Food Productivity"));
                    names.append(QStringLiteral("Speedup Building Type"));
                    names.append(QStringLiteral("Speedup Building Range"));
                    names.append(QStringLiteral("Speedup Percentage"));
                    names.append(QStringLiteral("Speedup Object Type"));
                    names.append(QStringLiteral("Speedup Effect Type"));
                    names.append(QStringLiteral("Speedup Secondary Effect Type"));
                    names.append(QStringLiteral("Speedup Secondary Percentage"));
                    names.append(QStringLiteral("Civilization Name Override"));
                    names.append(QStringLiteral("Starting Scout ID"));
                    names.append(QStringLiteral("Relic Wood Production Rate"));
                    names.append(QStringLiteral("Relic Stone Production Rate"));
                    names.append(QStringLiteral("Chopping Gold Productivity"));
                    names.append(QStringLiteral("Foraging Wood Productivity"));
                    names.append(QStringLiteral("Hunter Productivity"));
                    names.append(QStringLiteral("Technology Reward Effect"));
                    names.append(QStringLiteral("Unit Repair Cost"));
                    names.append(QStringLiteral("Building Repair Cost"));
                    names.append(QStringLiteral("Elevation Higher Damage"));
                    names.append(QStringLiteral("Elevation Lower Damage"));
                    names.append(QStringLiteral("Infantry Kill Reward"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Military Can Convert"));
                    names.append(QStringLiteral("Military Conversion Range"));
                    names.append(QStringLiteral("Military Conversion Chance"));
                    names.append(QStringLiteral("Military Conversion Recharge Rate"));
                    names.append(QStringLiteral("Spawn Inside"));
                    names.append(QStringLiteral("Cavalry Kill Reward")); // 284
                    names.append(QStringLiteral("Shared Visibility"));
                    names.append(QStringLiteral("Shared Exploration"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Killed Gaia"));
                    names.append(QStringLiteral("Killed P1"));
                    names.append(QStringLiteral("Killed P2"));
                    names.append(QStringLiteral("Killed P3"));
                    names.append(QStringLiteral("Killed P4"));
                    names.append(QStringLiteral("Killed P5"));
                    names.append(QStringLiteral("Killed P6"));
                    names.append(QStringLiteral("Killed P7"));
                    names.append(QStringLiteral("Killed P8"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Kills by Gaia"));
                    names.append(QStringLiteral("Kills by P1"));
                    names.append(QStringLiteral("Kills by P2"));
                    names.append(QStringLiteral("Kills by P3"));
                    names.append(QStringLiteral("Kills by P4"));
                    names.append(QStringLiteral("Kills by P5"));
                    names.append(QStringLiteral("Kills by P6"));
                    names.append(QStringLiteral("Kills by P7"));
                    names.append(QStringLiteral("Kills by P8"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Gaia Razings"));
                    names.append(QStringLiteral("P1 Razings"));
                    names.append(QStringLiteral("P2 Razings"));
                    names.append(QStringLiteral("P3 Razings"));
                    names.append(QStringLiteral("P4 Razings"));
                    names.append(QStringLiteral("P5 Razings"));
                    names.append(QStringLiteral("P6 Razings"));
                    names.append(QStringLiteral("P7 Razings"));
                    names.append(QStringLiteral("P8 Razings"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Razings by Gaia"));
                    names.append(QStringLiteral("Razings by P1"));
                    names.append(QStringLiteral("Razings by P2"));
                    names.append(QStringLiteral("Razings by P3"));
                    names.append(QStringLiteral("Razings by P4"));
                    names.append(QStringLiteral("Razings by P5"));
                    names.append(QStringLiteral("Razings by P6"));
                    names.append(QStringLiteral("Razings by P7"));
                    names.append(QStringLiteral("Razings by P8"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Gaia Kill Value"));
                    names.append(QStringLiteral("P1 Kill Value"));
                    names.append(QStringLiteral("P2 Kill Value"));
                    names.append(QStringLiteral("P3 Kill Value"));
                    names.append(QStringLiteral("P4 Kill Value"));
                    names.append(QStringLiteral("P5 Kill Value"));
                    names.append(QStringLiteral("P6 Kill Value"));
                    names.append(QStringLiteral("P7 Kill Value"));
                    names.append(QStringLiteral("P8 Kill Value"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Gaia Razing Value"));
                    names.append(QStringLiteral("P1 Razing Value"));
                    names.append(QStringLiteral("P2 Razing Value"));
                    names.append(QStringLiteral("P3 Razing Value"));
                    names.append(QStringLiteral("P4 Razing Value"));
                    names.append(QStringLiteral("P5 Razing Value"));
                    names.append(QStringLiteral("P6 Razing Value"));
                    names.append(QStringLiteral("P7 Razing Value"));
                    names.append(QStringLiteral("P8 Razing Value"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Gaia Tribute"));
                    names.append(QStringLiteral("P1 Tribute"));
                    names.append(QStringLiteral("P2 Tribute"));
                    names.append(QStringLiteral("P3 Tribute"));
                    names.append(QStringLiteral("P4 Tribute"));
                    names.append(QStringLiteral("P5 Tribute"));
                    names.append(QStringLiteral("P6 Tribute"));
                    names.append(QStringLiteral("P7 Tribute"));
                    names.append(QStringLiteral("P8 Tribute"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Tribute from Gaia"));
                    names.append(QStringLiteral("Tribute from P1"));
                    names.append(QStringLiteral("Tribute from P2"));
                    names.append(QStringLiteral("Tribute from P3"));
                    names.append(QStringLiteral("Tribute from P4"));
                    names.append(QStringLiteral("Tribute from P5"));
                    names.append(QStringLiteral("Tribute from P6"));
                    names.append(QStringLiteral("Tribute from P7"));
                    names.append(QStringLiteral("Tribute from P8"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused"));
                    names.append(QStringLiteral("Unused")); // 499
                }
            }
        }
    }
    else
    {
        names.append(QStringLiteral("Food Storage"));
        names.append(QStringLiteral("Carbon Storage"));
        names.append(QStringLiteral("Ore Storage"));
        names.append(QStringLiteral("Nova Storage"));
        names.append(QStringLiteral("Population Headroom"));
        names.append(QStringLiteral("Conversion Range"));
        names.append(QStringLiteral("Current Tech Level"));
        names.append(QStringLiteral("Holocrons Captured"));
        names.append(QStringLiteral("Unused (Trade Bonus)"));
        names.append(QStringLiteral("Trade Goods"));
        names.append(QStringLiteral("Recharge Rate of Shields"));
        names.append(QStringLiteral("Current Population"));
        names.append(QStringLiteral("Corpse Decay Time"));
        names.append(QStringLiteral("Remarkable Discovery"));
        names.append(QStringLiteral("Monuments Captured"));
        names.append(QStringLiteral("Meat Storage"));
        names.append(QStringLiteral("Berry Storage"));
        names.append(QStringLiteral("Fish Storage"));
        names.append(QStringLiteral("Power Core Range"));
        names.append(QStringLiteral("Unpowered Building Work Rate Multiplier"));
        names.append(QStringLiteral("Units Killed"));
        names.append(QStringLiteral("Technology Count"));
        names.append(QStringLiteral("% Map Explored"));
        names.append(QStringLiteral("Submarine Detection"));
        names.append(QStringLiteral("Shield Generator Range"));
        names.append(QStringLiteral("Shield Recharge Interval"));
        names.append(QStringLiteral("Drop-off Time of Shields"));
        names.append(QStringLiteral("Enable Jedi Conversion"));
        names.append(QStringLiteral("Enable Building Conversion"));
        names.append(QStringLiteral("Fambaa Shield Generator Range"));
        names.append(QStringLiteral("Unused (Building Limit)"));
        names.append(QStringLiteral("Enable A-A Attack for AT-AT"));
        names.append(QStringLiteral("Bonus Population Cap"));
        names.append(QStringLiteral("Power Core Shielding"));
        names.append(QStringLiteral("Force"));
        names.append(QStringLiteral("Force Recharging Rate"));
        names.append(QStringLiteral("Farm Food Amount"));
        names.append(QStringLiteral("Civilian Population"));
        names.append(QStringLiteral("Shields On for Bombers/Fighters"));
        names.append(QStringLiteral("All Techs Achieved"));
        names.append(QStringLiteral("Military Population"));
        names.append(QStringLiteral("Conversions"));
        names.append(QStringLiteral("Standing Monuments"));
        names.append(QStringLiteral("Razings"));
        names.append(QStringLiteral("Kill Ratio"));
        names.append(QStringLiteral("Survival to Finish"));
        names.append(QStringLiteral("Tribute Inefficiency"));
        names.append(QStringLiteral("Building Self Regeneration Timer"));
        names.append(QStringLiteral("Town Center Unavailable"));
        names.append(QStringLiteral("Gold Counter"));
        names.append(QStringLiteral("Reveal Ally"));
        names.append(QStringLiteral("Shielding"));
        names.append(QStringLiteral("Monasteries"));
        names.append(QStringLiteral("Tribute Sent"));
        names.append(QStringLiteral("All Ruins Captured"));
        names.append(QStringLiteral("All Relics Captured"));
        names.append(QStringLiteral("Enable Stealth for Masters"));
        names.append(QStringLiteral("Kidnap Storage"));
        names.append(QStringLiteral("Masters Can See Hidden Units"));
        names.append(QStringLiteral("Tech Level 1 Tech ID"));
        names.append(QStringLiteral("Tech Level 2 Tech ID"));
        names.append(QStringLiteral("Tech Level 3 Tech ID"));
        names.append(QStringLiteral("Building Housing Rate"));
        names.append(QStringLiteral("Tech Level 4 Tech ID"));
        names.append(QStringLiteral("Gather Accumulator"));
        names.append(QStringLiteral("Salvage Decay Rate"));
        names.append(QStringLiteral("Unused (Allow Formations)"));
        names.append(QStringLiteral("Can Convert"));
        names.append(QStringLiteral("Hit Points Killed"));
        names.append(QStringLiteral("Killed P1"));
        names.append(QStringLiteral("Killed P2"));
        names.append(QStringLiteral("Killed P3"));
        names.append(QStringLiteral("Killed P4"));
        names.append(QStringLiteral("Killed P5"));
        names.append(QStringLiteral("Killed P6"));
        names.append(QStringLiteral("Killed P7"));
        names.append(QStringLiteral("Killed P8"));
        names.append(QStringLiteral("Conversion Resistance"));
        names.append(QStringLiteral("Trade Vig Rate"));
        names.append(QStringLiteral("Ore Mining Productivity"));
        names.append(QStringLiteral("Queued Units"));
        names.append(QStringLiteral("Training Count"));
        names.append(QStringLiteral("Start with Packed Town Center"));
        names.append(QStringLiteral("Boarding Recharge Rate"));
        names.append(QStringLiteral("Starting Villagers"));
        names.append(QStringLiteral("Tech Cost Modifier"));
        names.append(QStringLiteral("Tech Time Modifier"));
        names.append(QStringLiteral("Concentration"));
        names.append(QStringLiteral("Fish Trap Food Amount"));
        names.append(QStringLiteral("Medic Healing Rate"));
        names.append(QStringLiteral("Healing Range"));
        names.append(QStringLiteral("Starting Food"));
        names.append(QStringLiteral("Starting Carbon"));
        names.append(QStringLiteral("Starting Ore"));
        names.append(QStringLiteral("Starting Nova"));
        names.append(QStringLiteral("Enable PTWC / Kidnap / Loot"));
        names.append(QStringLiteral("Berserker Heal Timer"));
        names.append(QStringLiteral("Dominant Sheep Control"));
        names.append(QStringLiteral("Object Cost Sum"));
        names.append(QStringLiteral("Tech Cost Sum"));
        names.append(QStringLiteral("Holocron Nova Sum"));
        names.append(QStringLiteral("Trade Income Sum"));
        names.append(QStringLiteral("P1 Tribute"));
        names.append(QStringLiteral("P2 Tribute"));
        names.append(QStringLiteral("P3 Tribute"));
        names.append(QStringLiteral("P4 Tribute"));
        names.append(QStringLiteral("P5 Tribute"));
        names.append(QStringLiteral("P6 Tribute"));
        names.append(QStringLiteral("P7 Tribute"));
        names.append(QStringLiteral("P8 Tribute"));
        names.append(QStringLiteral("P1 Kill Value"));
        names.append(QStringLiteral("P2 Kill Value"));
        names.append(QStringLiteral("P3 Kill Value"));
        names.append(QStringLiteral("P4 Kill Value"));
        names.append(QStringLiteral("P5 Kill Value"));
        names.append(QStringLiteral("P6 Kill Value"));
        names.append(QStringLiteral("P7 Kill Value"));
        names.append(QStringLiteral("P8 Kill Value"));
        names.append(QStringLiteral("P1 Razings"));
        names.append(QStringLiteral("P2 Razings"));
        names.append(QStringLiteral("P3 Razings"));
        names.append(QStringLiteral("P4 Razings"));
        names.append(QStringLiteral("P5 Razings"));
        names.append(QStringLiteral("P6 Razings"));
        names.append(QStringLiteral("P7 Razings"));
        names.append(QStringLiteral("P8 Razings"));
        names.append(QStringLiteral("P1 Razing Value"));
        names.append(QStringLiteral("P2 Razing Value"));
        names.append(QStringLiteral("P3 Razing Value"));
        names.append(QStringLiteral("P4 Razing Value"));
        names.append(QStringLiteral("P5 Razing Value"));
        names.append(QStringLiteral("P6 Razing Value"));
        names.append(QStringLiteral("P7 Razing Value"));
        names.append(QStringLiteral("P8 Razing Value"));
        names.append(QStringLiteral("Standing Fortresses"));
        names.append(QStringLiteral("Hit Points Razed"));
        names.append(QStringLiteral("Kills by P1"));
        names.append(QStringLiteral("Kills by P2"));
        names.append(QStringLiteral("Kills by P3"));
        names.append(QStringLiteral("Kills by P4"));
        names.append(QStringLiteral("Kills by P5"));
        names.append(QStringLiteral("Kills by P6"));
        names.append(QStringLiteral("Kills by P7"));
        names.append(QStringLiteral("Kills by P8"));
        names.append(QStringLiteral("Razings by P1"));
        names.append(QStringLiteral("Razings by P2"));
        names.append(QStringLiteral("Razings by P3"));
        names.append(QStringLiteral("Razings by P4"));
        names.append(QStringLiteral("Razings by P5"));
        names.append(QStringLiteral("Razings by P6"));
        names.append(QStringLiteral("Razings by P7"));
        names.append(QStringLiteral("Razings by P8"));
        names.append(QStringLiteral("Value Killed by Others"));
        names.append(QStringLiteral("Value Razed by Others"));
        names.append(QStringLiteral("Killed by Others"));
        names.append(QStringLiteral("Razed by Others"));
        names.append(QStringLiteral("Tribute from P1"));
        names.append(QStringLiteral("Tribute from P2"));
        names.append(QStringLiteral("Tribute from P3"));
        names.append(QStringLiteral("Tribute from P4"));
        names.append(QStringLiteral("Tribute from P5"));
        names.append(QStringLiteral("Tribute from P6"));
        names.append(QStringLiteral("Tribute from P7"));
        names.append(QStringLiteral("Tribute from P8"));
        names.append(QStringLiteral("Value Current Units"));
        names.append(QStringLiteral("Value Current Buildings"));
        names.append(QStringLiteral("Food Total"));
        names.append(QStringLiteral("Carbon Total"));
        names.append(QStringLiteral("Ore Total"));
        names.append(QStringLiteral("Nova Total"));
        names.append(QStringLiteral("Total Value of Kills"));
        names.append(QStringLiteral("Total Tribute Received"));
        names.append(QStringLiteral("Total Value of Razings"));
        names.append(QStringLiteral("Total Fortresses Built"));
        names.append(QStringLiteral("Total Monuments Built"));
        names.append(QStringLiteral("Tribute Score"));
        names.append(QStringLiteral("Convert Min Adjustment"));
        names.append(QStringLiteral("Convert Max Adjustment"));
        names.append(QStringLiteral("Convert Resist Min Adjustment"));
        names.append(QStringLiteral("Convert Resist Max Adjustment"));
        names.append(QStringLiteral("Convert Building Min"));
        names.append(QStringLiteral("Convert Building Max"));
        names.append(QStringLiteral("Convert Building Chance"));
        names.append(QStringLiteral("Reveal Enemy"));
        names.append(QStringLiteral("Value Wonders Castles"));
        names.append(QStringLiteral("Food Score"));
        names.append(QStringLiteral("Carbon Score"));
        names.append(QStringLiteral("Ore Score"));
        names.append(QStringLiteral("Nova Score"));
        names.append(QStringLiteral("Carbon Gathering Productivity"));
        names.append(QStringLiteral("Food-gathering Productivity"));
        names.append(QStringLiteral("Holocron Nova Production Rate"));
        names.append(QStringLiteral("Converted Units Die"));
        names.append(QStringLiteral("Meditation"));
        names.append(QStringLiteral("Crenellations"));
        names.append(QStringLiteral("Construction Rate Modifier"));
        names.append(QStringLiteral("Hun Wonder Bonus"));
        names.append(QStringLiteral("Spies Discount"));
        names.append(QStringLiteral("Unknown"));
        names.append(QStringLiteral("Unknown"));
        names.append(QStringLiteral("Misc Counter 1"));
        names.append(QStringLiteral("Misc Counter 2"));
        names.append(QStringLiteral("Misc Counter 3"));
        names.append(QStringLiteral("Misc Counter 4"));
        names.append(QStringLiteral("Misc Counter 5"));
        names.append(QStringLiteral("Unknown"));
        names.append(QStringLiteral("Unknown"));
        names.append(QStringLiteral("Unknown"));
        names.append(QStringLiteral("Unknown"));
        names.append(QStringLiteral("Unknown"));
        if (version >= genie::GV_CC)
        {
            names.append(QStringLiteral("Unknown"));
            if (version >= genie::GV_CCV2)
            {
                names.append(QStringLiteral("Buildings are self powered"));
                names.append(QStringLiteral("Aircraft Regenerates Hit Points"));
                names.append(QStringLiteral("Max Force After Conversion"));
                names.append(QStringLiteral("Nova Mining Productivity"));
                names.append(QStringLiteral("Nova generation rate (small)"));
                names.append(QStringLiteral("Nova generation rate (large)"));
                names.append(QStringLiteral("Ore generation rate"));
                names.append(QStringLiteral("Food generation rate"));
            }
        }
    }
    return names;
}

} // namespace

const QStringList &resourceNames(genie::GameVersion version)
{
    static QHash<int, QStringList> cache;
    auto it = cache.find(version);
    if (it == cache.end())
        it = cache.insert(version, buildResourceNames(version));
    return *it;
}

QString resourceName(genie::GameVersion version, int id)
{
    const QStringList &names = resourceNames(version);
    return id >= 0 && id < names.size() ? names.at(id) : QString();
}

} // namespace newage
